author: SDWebImageSwiftUI
module-version: 1.5.0
module: SDWebImageSwiftUI
output: "./docs"
theme: "./jazzy-theme/themes/apple"
xcodebuild_arguments:
    - "CODE_SIGNING_ALLOWED"
    - "NO"
    - "-project"
    - "SDWebImageSwiftUI.xcodeproj"
    - "-scheme"
    - "SDWebImageSwiftUI"
min-acl: internal
