clean: true
author: SDWebImageSwiftUI
module-version: 1.5.0
module: SDWebImageSwiftUI
output: "./docs"
theme: "./jazzy-theme/themes/apple"
xcodebuild_arguments:
  ["-project", "SDWebImageSwiftUI.xcodeproj", "-scheme", "SDWebImageSwiftUI", "-sdk", "iphonesimulator"]
podspec: SDWebImageSwiftUI.podspec
