author: SDWebImageSwiftUI
github_url: https://github.com/SDWebImage/SDWebImageSwiftUI
github-file-prefix: https://github.com/SDWebImage/SDWebImageSwiftUI/tree/1.5.0 
module-version: 1.5.0
module: SDWebImageSwiftUI
output: "./docs"
theme: "./jazzy-theme/themes/apple"
