name: Jazzy

on:
  push:
    # Push target branch toggle action.
    branches: [ action ]

jobs:
  # Job named build.
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install jazzy.
      run: gem install jazzy
    - name: Jazzy path.
      run: jazzy --path
