name: Jazzy

on:
  push:
    # Push target branch toggle action.
    branches: [ action ]

jobs:
  # Job named build.
  build:

    runs-on: macos-latest
    env:
      GEM_VERSION: $(gem -v)
    steps:
    - uses: actions/checkout@v2
    - name: Install jazzy.
      run: gem install jazzy
    - name: Clone themes.
      run: git clone git@github.com:SDWebImage/jazzy-theme.git ../jazzy-theme
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Generate docs.
      run: jazzy \
          --swift \
          --author SDWebImageSwiftUI \
          --github_url https://github.com/SDWebImage/SDWebImageSwiftUI \
          --module-version 1.5.0 \
          --umbrella-header SDWebImageSwiftUI/SDWebImageSwiftUI.h \
          --undocumented-text "" \
          --module SDWebImageSwiftUI \
          --framework-root . \
          --sdk iphonesimulator \
          --output ../sdwebimage.github.io/SDWebImageSwiftUI \
          --theme ../jazzy-theme/themes/apple
    - name: List files.
      run: ls ../sdwebimage.github.io/SDWebImageSwiftUI
    
